### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by johannesbottcher** [razueroh/master-doctoral-thesis-template#1]
Hi there, 
the main resoource for the template is LaTeX-templates.com. Meanwhile, there have been some updates and more will come. If you are interested, check it out.

**Comment by razueroh** [comment]
Hi @johannesbottcher,
I changed the link to the main source [here](http://www.latextemplates.com/template/masters-doctoral-thesis). Also, I added the updates for the template and I'll be waiting for the new ones. Thanks for the comment.

**Comment by johannesbottcher** [comment]
Alight, if you have any suggetions for improvement, don't hesitate to ping us. I cannot promise though that everthing will be made possible.

**Comment by razueroh** [comment]
@johannesbottcher Ok, thanks. I'll let you know if I have any suggestion.
